---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket 
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 Bucket to create
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      BucketName:
        default: S3 Bucket Name

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        -
          Key: Name
          Value: !Ref BucketName

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowSSLRequestsOnly 
          Effect: Deny
          Principal:
            AWS: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref 'AWS::AccountId'
                - ':root'
          Action: 's3:*'
          Resource:
          - !GetAtt 'S3Bucket.Arn'
          - !Sub '${S3Bucket.Arn}/*'
          Condition:
            Bool:
              'aws:SecureTransport': false
                    - 
        - Sid: "DenyIncorrectEncryptionHeader"
          Effect: "Deny"
          Principal:
            AWS: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref 'AWS::AccountId'
                - ':root'
          Action: "s3:PutObject"
          Resource:
            - !Sub '${S3Bucket.Arn}/*'
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption: 
              - AES256
              - aws:kms
        - Sid: "DenyUnEncryptedObjectUploads"
          Effect: "Deny"
          Principal:
            AWS: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref 'AWS::AccountId'
                - ':root'
          Action: "s3:PutObject"
          Resource:
              - !Sub '${S3Bucket.Arn}/*'
          Condition:
            "Null":
              s3:x-amz-server-side-encryption: "true"

Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Description: S3 Bucket for object storage
